# Generated by Django 5.2.4 on 2025-07-26 05:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_address', models.CharField(blank=True, max_length=200)),
                ('destination_address', models.CharField(blank=True, max_length=200)),
                ('departure_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('available_seats', models.PositiveIntegerField()),
                ('distance_km', models.FloatField(default=0.0)),
                ('co2_saved', models.FloatField(default=0.0)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_booked', models.PositiveIntegerField(default=1)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShareRouteApp.ride')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('is_driver', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShareRouteApp.userprofile'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('license_plate', models.CharField(blank=True, max_length=20, unique=True)),
                ('is_electric', models.BooleanField(default=False)),
                ('vehicle_document', models.FileField(blank=True, null=True, upload_to='vehicle_docs/')),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShareRouteApp.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='ride',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShareRouteApp.vehicle'),
        ),
    ]
